---
# tasks file for k8s-workers
- name: Copy K3s environment file
  register: k3senv
  template:
    src: "k3s-agent-service.env.j2"
    dest: "{{ systemd_dir }}/k3s-agent-service.env"
    owner: root
    group: root
    mode: 0644

- name: Copy K3s service file
  template:
    src: "k3s-agent.service.j2"
    dest: "{{ systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-agent
    daemon_reload: yes
    state: restarted
    enabled: yes